<a href="https://colab.research.google.com/github/sumanu9400/Numerical_python/blob/main/numerical_python(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical python part-01

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
a= np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Initial Placeholders

In [ ]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
arr=np.ones((4,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr=np.eye(5,k=1)
print(arr)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr=np.full((4,3),6)
print(arr)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


In [ ]:
arr=np.empty((4,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
arr=np.linspace(1,25,5) # distance between two num in 5
print(arr)

[ 1.  7. 13. 19. 25.]


In [ ]:
arr=np.arange(1,25) # distance between two num in 5
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [ ]:
arr=np.arange(1,25,2) # distance between two num in 5
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [ ]:
arr=np.random.random((3,3))
print(arr)

[[0.92862595 0.01955536 0.18262804]
 [0.56783641 0.82847185 0.27430469]
 [0.36817615 0.64777686 0.31774046]]


In [ ]:
arr=np.random.rand(5,2)
print(arr)

[[0.73751374 0.68232593]
 [0.61773003 0.58712103]
 [0.76874477 0.75523783]
 [0.68341896 0.56789881]
 [0.32317985 0.70948642]]


In [ ]:
arr=np.random.randn(5,3)
print(arr)

[[-1.34550915 -1.39727516  2.04172551]
 [ 2.28198597  0.6076202  -1.56966572]
 [-0.06718595  0.16730062 -1.46752834]
 [ 0.60152593  0.7787423  -0.19570356]
 [ 1.37435458  1.18096961 -0.56121693]]


In [ ]:
arr=np.random.randint(1,100,5) #1 to 100 and 5 random numbers
print(arr)

[54 74 21 22 22]


In [ ]:
arr=np.random.choice([10,20,30,40,50,60],size=(4))
print(arr)

[20 20 50 60]


In [ ]:
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[4 5 1 3 2]


In [ ]:
arr=np.array([1,2,3,3,3,4,5])
print(np.unique(arr))

[1 2 3 4 5]


In [ ]:
arr=np.array([1,2,3,4,5])
arr2=np.array([[6,7,8],[9,10,11]])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
arr.ndim

1

In [ ]:
arr2.ndim

2

In [ ]:
arr.size

5

In [ ]:
arr.shape

(5,)

In [ ]:
arr2.shape

(2, 3)

In [ ]:
len(arr)

5

In [ ]:
len(arr2)

2

Numpy datatypes


In [ ]:
a=np.array([[4,5,6],[7,8,9]],dtype='bool')
print(a)

[[ True  True  True]
 [ True  True  True]]


In [ ]:
a=np.array([[4,5,6],[7,8,9]],dtype='float')
print(a)

[[4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
a=np.array([[4,5,6],[7,8,9]],dtype='int')
print(a)

[[4 5 6]
 [7 8 9]]


In [ ]:
a=np.array([[4,5,6],[7,8,9]],dtype='complex')
print(a)

[[4.+0.j 5.+0.j 6.+0.j]
 [7.+0.j 8.+0.j 9.+0.j]]


In [ ]:
a=np.array([1,2.5,"python"])
print(a)

['1' '2.5' 'python']


In [ ]:
a=np.array([1,2.5,"python"], dtype='object')
print(a)

[1 2.5 'python']


In [ ]:
a=np.array(['hello','suman','are','you','learning','python'],dtype='U3')
print(a)

['hel' 'sum' 'are' 'you' 'lea' 'pyt']


Indexing and Slicing part-02

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([[6,7,8],[9,10,11]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
print(arr1[2])

3


In [ ]:
print(arr1[-3])

3


In [ ]:
print(arr2[0])

[6 7 8]


In [ ]:
print(arr2[1])

[ 9 10 11]


In [ ]:
print(arr2[1,1])

10


In [ ]:
arr4=np.random.randint(1,10,(3,3,3))
print(arr4)

[[[2 3 2]
  [2 9 2]
  [6 6 2]]

 [[9 2 2]
  [8 1 2]
  [3 5 8]]

 [[7 1 9]
  [3 4 6]
  [2 9 8]]]


In [ ]:
print(arr4[1,2,2])

8


Slicing

array[row_start : row_stop : row_step ,col_start : col_stop : col_step]

In [ ]:
arr=np.arange(21,31)
print(arr)

[21 22 23 24 25 26 27 28 29 30]


In [ ]:
print(arr[3:9])

[24 25 26 27 28 29]


In [ ]:
print(arr[3:9:2])# 2 is step

[24 26 28]


In [ ]:
print(arr[:5])

[21 22 23 24 25]


In [ ]:
print(arr[5:])

[26 27 28 29 30]


In [ ]:
arr4= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(arr4[0:2,0:2])

[[1 2]
 [4 5]]


In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# prompt: single step print 8 and 9 numbers

import numpy as np

# Redefine arr2 as it might not be defined in the current context
arr2=np.array([[6,7,8],[9,10,11]])

# Print 8 and 9 from arr2
print(arr2[0, 2], arr2[1, 0])

8 9


In [ ]:
print(arr1)

[1 2 3 4 5]


In [ ]:
print(arr1>2)

[False False  True  True  True]


In [ ]:
print(arr1[arr1>2])

[3 4 5]


In [ ]:
print(arr1[arr1%2==0])

[2 4]


In [ ]:
indices=[0,2,4]
print(arr1[indices])

[1 3 5]


functions

updating array elements


In [ ]:
arr1=[21,22,23,24,25,26,27,28,29,30]
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr2)

[21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr1[4] = 50
print(arr1)

[21, 22, 23, 24, 50, 26, 27, 28, 29, 30]


In [ ]:
arr1 = np.array(arr1)
arr1[arr1%2==0] = 0
print(arr1)

[21  0 23  0  0  0 27  0 29  0]


In [ ]:
indices=[0,2,4]
new_values=[100,200,300]
arr1[indices]=new_values
print(arr1)

[100   0 200   0 300   0  27   0  29   0]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr[0,2]=70
print(arr)

[[ 1  2 70]
 [ 4  5  6]]


In [ ]:
arr[0:2,0:2]=[[10,20],[30,40]]
print(arr)

[[10 20 70]
 [30 40  6]]


Removing Array Elements



In [ ]:
print(arr1)

[100   0 200   0 300   0  27   0  29   0]


In [ ]:
np.delete(arr1,4)

array([100,   0, 200,   0,   0,  27,   0,  29,   0])

In [ ]:
np.delete(arr1,[0,3])

array([  0, 200, 300,   0,  27,   0,  29,   0])

In [ ]:
print(arr)

[[10 20 70]
 [30 40  6]]


In [ ]:
np.delete(arr,(0,1))

array([70, 30, 40,  6])

In [ ]:
np.delete(arr,1,axis=0)

array([[10, 20, 70]])

In [ ]:
np.delete(arr,0,axis=1)

array([[20, 70],
       [40,  6]])

In [ ]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
np.delete(arr3,1,axis=0)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
np.delete(arr3,0,axis=1)

array([[[ 4,  5,  6]],

       [[10, 11, 12]]])

In [ ]:
np.delete(arr3,1,axis=2)

array([[[ 1,  3],
        [ 4,  6]],

       [[ 7,  9],
        [10, 12]]])

In [ ]:
np.delete(arr3,[0,1],axis=2)

array([[[ 3],
        [ 6]],

       [[ 9],
        [12]]])

Copy and view Array

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
x=arr.copy()
x

array([1, 2, 3, 4, 5])

In [ ]:
y=arr.view()
y

array([1, 2, 3, 4, 5])

In [ ]:
x[2]=100
x

array([  1,   2, 100,   4,   5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
y[2]=100
y

array([  1,   2, 100,   4,   5])

In [ ]:
arr

array([  1,   2, 100,   4,   5])

Find Unique Elements


In [ ]:
arr_1d=np.array([1,2,1,4,2,5,6,2,8,1])
print(arr_1d)

[1 2 1 4 2 5 6 2 8 1]


In [ ]:
np.unique(arr_1d)

array([1, 2, 4, 5, 6, 8])

In [ ]:
arr_2d=np.array([[1,2,3],[4,2,5],[1,2,3]])
print(arr_2d)

[[1 2 3]
 [4 2 5]
 [1 2 3]]


In [ ]:
np.unique(arr_2d)

array([1, 2, 3, 4, 5])

In [ ]:
np.unique(arr_2d,axis=0) #rows dalete

array([[1, 2, 3],
       [4, 2, 5]])

In [ ]:
np.unique(arr_2d,axis=1) # col delete

array([[1, 2, 3],
       [4, 2, 5],
       [1, 2, 3]])

sorting

In [ ]:
arr=np.array([1,2,1,4,2,5,6,2,8,1])
np.sort(arr)

array([1, 1, 1, 2, 2, 2, 4, 5, 6, 8])

In [ ]:
print(arr_2d)

[[1 2 3]
 [4 2 5]
 [1 2 3]]


In [ ]:
np.sort(arr_2d)

array([[1, 2, 3],
       [2, 4, 5],
       [1, 2, 3]])

Numpy array part-03(master array manipulation)

In [ ]:
arr=np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
reshaped_arr=arr.reshape(3,4)
print(reshaped_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
reshaped_arr=arr.reshape(2,3,2)
print(reshaped_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
flatten_arr=arr.flatten()
print(flatten_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
ravel_arr=arr.ravel()
print(ravel_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Concatenating Arrays vertically and horizontally

In [ ]:
arr1=np.arange(12,24).reshape(3,4)
print(arr1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
arr2=np.arange(0,12).reshape(3,4)
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
vertical_concat=np.vstack((arr1,arr2))
print(vertical_concat)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
vertical_concat=np.vstack((arr1+arr2))
print(vertical_concat)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [ ]:
split_arr=np.split(arr1,2,axis=1)
print(split_arr)

[array([[12, 13],
       [16, 17],
       [20, 21]]), array([[14, 15],
       [18, 19],
       [22, 23]])]


Fliping Array

In [ ]:
arr1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.flipud(arr1)

array([[20, 21, 22, 23],
       [16, 17, 18, 19],
       [12, 13, 14, 15]])

In [ ]:
np.fliplr(arr1)


array([[15, 14, 13, 12],
       [19, 18, 17, 16],
       [23, 22, 21, 20]])